---
- name: Install functioning SmokePing service in Vagrant VM
  hosts: all
  vars:
    timezone: America/Phoenix
    IPv4:
      IPv4_Hosts:
        - {name: Router1, address: 192.168.128.12}
        - {name: Router2, address: 3.3.3.34}
    IPv6:
      IPv6_Hosts:
        - {name: GoogleDNS, address: "2001:4860:4860::8888"}

  tasks:

    - name: set localtime
      copy: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime
      become: true

    - name: set timezone
      template: src=templates/timezone dest=/etc/timezone
      become: true

    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
      become: true

    - name: Create Target file for Smokeping using Jinja2
      template:
        src: ./templates/targets.j2
        dest: ~/Targets

    - name: ensure smokeping is installed
      apt: name=smokeping update_cache=yes
      become: true

    - name: soft-link for apache2 configuration in conf-available
      file: src=/etc/smokeping/apache2.conf dest=/etc/apache2/conf-available/smokeping.conf state=link
      become: true
      notify:
      - restart apache2

    - name: copy configuration files to appropriate location (except Targets)
      command: cp -r /vagrant/config.d /etc/smokeping/
      become: true
      notify:
      - restart apache2

    - name: copy Targets file into config.d
      command: cp /home/vagrant/Targets /etc/smokeping/config.d/
      become: true
      notify:
      - restart apache2

    - name: enable cgid in apache2
      command: a2enmod cgid
      become: true
      notify:
      - restart apache2

    - name: enable smokeping in apache2
      command: a2enconf smokeping
      become: true
      notify:
      - restart apache2

    - name: restart smokeping service
      service: name=smokeping state=restarted
      become: true

  handlers:



    - name: restart apache2
      service: name=apache2 state=restarted
      become: true
